default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: root
  # password:
  # host: localhost

development:
  <<: *default
  database: webapp_development
  username: root
  password: <%= ENV["MYSQL_ROOT_PASSWORD"] %>
  # ホスト名はdocker-compose.ymlにあるDB用のサービス名「db」を指定
  host: db

test:
  <<: *default
  database: webapp_test
  username: root
  password: <%= ENV["MYSQL_ROOT_PASSWORD"] %>
  host: db

production:
  <<: *default
  database: webapp_production
  username: webapp
  password: <%= ENV["WEBAPP_DATABASE_PASSWORD"] %>
