default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV.fetch("DATABASE_PORT") {3306} %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV["MYSQL_ROOT_PASSWORD"] %>
  host: db
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: webapp_development

test:
  <<: *default
  database: webapp_test

production:
  <<: *default
  database: webapp_production
  username: webapp
  password: <%= ENV["WEBAPP_DATABASE_PASSWORD"] %>
